import { ReviewActions } from "@/components/review-actions";
import { explorer } from "@/lib/chain";
import { readContribution } from "@/lib/onchain";
export default async function ContributionPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params; let item: Awaited<ReturnType<typeof readContribution>> | null = null; try { item = await readContribution(id as `0x${string}`); } catch {}
  if (!item) return <div className="page"><section className="panel form-panel"><span className="badge" data-tone="danger">Unavailable</span><h1>Contribution could not be read</h1></section></div>;
  return <div className="page detail-layout"><section className="panel form-panel contribution-record"><div className="cluster"><span className="badge" data-tone={item.archivedAt === "0" ? "active" : "danger"}>{item.archivedAt === "0" ? "Active" : "Archived"}</span><span className="badge">Monad Testnet</span></div><h1 className="section-title">Contribution record</h1><dl className="review-list composer-fields"><div><dt>ID</dt><dd className="data">{id}</dd></div><div><dt>Creator</dt><dd><a href={`/profiles/${item.creatorProfileId}`}>{item.creatorProfileId}</a></dd></div><div><dt>Artifact SHA-256</dt><dd>{item.artifactDigest}</dd></div><div><dt>Metadata digest</dt><dd>{item.metadataDigest}</dd></div><div><dt>Metadata</dt><dd>{item.metadataURI}</dd></div><div><dt>Registered by</dt><dd><a href={explorer.address(item.registeredBy)}>{item.registeredBy}</a></dd></div></dl><div className="cluster"><a className="pill pill-primary" href={`/verify?type=contribution&id=${id}`}>Verify and export</a><a className="pill pill-secondary" href={explorer.address(contractsAddress)}>Explorer</a></div><div className="indexer-lag"><span className="badge" data-tone="pending">Projection pending</span><p>Onchain data is available. Indexed claim counts appear after Envio catches up.</p></div></section><ReviewActions contributionId={id as `0x${string}`} /></div>;
}
const contractsAddress = "0x7BFB7e4A6325FC7Dd9141A13039B978852AF6c65";
