import { ReviewActions } from "@/components/review-actions";
import { explorer } from "@/lib/chain";
import { contracts } from "@/lib/contracts.generated";
import { indexerQuery } from "@/lib/indexer";
import { readContribution } from "@/lib/onchain";
export default async function ContributionPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params; let item: Awaited<ReturnType<typeof readContribution>> | null = null; try { item = await readContribution(id as `0x${string}`); } catch {}
  if (!item) return <div className="page"><section className="panel form-panel"><span className="badge" data-tone="danger">Unavailable</span><h1>Contribution could not be read</h1></section></div>;
  const projection = process.env.NEXT_PUBLIC_ENVIO_GRAPHQL_URL ? await indexerQuery<{ Contribution_by_pk: { attestations: Array<{ selfAtIssuance: boolean; disputed: boolean; revokedAt: string | null; supersededBy: string | null }> } | null; ChainState_by_pk: { latestBlock: string } | null }>("query($id:String!,$chainId:Int!){Contribution_by_pk(id:$id,chainId:$chainId){attestations{selfAtIssuance disputed revokedAt supersededBy}} ChainState_by_pk(id:\"10143\",chainId:$chainId){latestBlock}}", { id, chainId: 10143 }).catch(() => null) : null;
  const activeClaims = projection?.Contribution_by_pk?.attestations.filter((claim) => claim.revokedAt == null && claim.supersededBy == null) ?? [];
  const externalClaims = activeClaims.filter((claim) => !claim.selfAtIssuance);
  return <div className="page detail-layout"><section className="panel form-panel contribution-record"><div className="cluster"><span className="badge" data-tone={item.archivedAt === "0" ? "active" : "danger"}>{item.archivedAt === "0" ? "Active" : "Archived"}</span><span className="badge">Monad Testnet</span></div><h1 className="section-title">Contribution record</h1><dl className="review-list composer-fields"><div><dt>ID</dt><dd className="data">{id}</dd></div><div><dt>Creator</dt><dd><a href={`/profiles/${item.creatorProfileId}`}>{item.creatorProfileId}</a></dd></div><div><dt>Artifact SHA-256</dt><dd>{item.artifactDigest}</dd></div><div><dt>Metadata digest</dt><dd>{item.metadataDigest}</dd></div><div><dt>Metadata</dt><dd>{item.metadataURI}</dd></div><div><dt>Registered by</dt><dd><a href={explorer.address(item.registeredBy)}>{item.registeredBy}</a></dd></div></dl><div className="cluster"><a className="pill pill-primary" href={`/verify?type=contribution&id=${id}`}>Verify and export</a><a className="pill pill-secondary" href={explorer.address(contracts.ContributionRegistry.address)}>Explorer</a></div>{projection?.Contribution_by_pk ? <div className="indexer-lag" role="status" aria-atomic="true"><span className="badge" data-tone="active">Indexed</span><p>{activeClaims.length} active claims · {externalClaims.length} external · {externalClaims.filter((claim) => claim.disputed).length} disputed · indexed through block {projection.ChainState_by_pk?.latestBlock ?? "unknown"}.</p></div> : <div className="indexer-lag" role="status" aria-atomic="true"><span className="badge" data-tone="pending">Projection pending</span><p>Onchain data is available. Indexed claim counts appear after Envio catches up.</p></div>}</section><ReviewActions contributionId={id as `0x${string}`} /></div>;
}
