// Generated by scripts/export-web-contracts.mjs. Do not edit.
export const chainId = 10143 as const;
export const deploymentBlock = 61841093n;
export const contracts = {
  "AttestiaProfileRegistry": {
    "address": "0x610b0399d82d8cE68E558a4f7a8CE87d84BdA32E",
    "abi": [
      {
        "type": "constructor",
        "inputs": [
          {
            "name": "initialOwner",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "identityRegistry_",
            "type": "address",
            "internalType": "address"
          }
        ],
        "stateMutability": "nonpayable"
      },
      {
        "type": "function",
        "name": "MAX_URI_LENGTH",
        "inputs": [],
        "outputs": [
          {
            "name": "",
            "type": "uint256",
            "internalType": "uint256"
          }
        ],
        "stateMutability": "view"
      },
      {
        "type": "function",
        "name": "agentPolicy",
        "inputs": [
          {
            "name": "agentId",
            "type": "uint256",
            "internalType": "uint256"
          }
        ],
        "outputs": [
          {
            "name": "",
            "type": "tuple",
            "internalType": "struct AttestiaProfileRegistry.AgentPolicy",
            "components": [
              {
                "name": "digest",
                "type": "bytes32",
                "internalType": "bytes32"
              },
              {
                "name": "uri",
                "type": "string",
                "internalType": "string"
              },
              {
                "name": "updatedAt",
                "type": "uint64",
                "internalType": "uint64"
              },
              {
                "name": "version",
                "type": "uint32",
                "internalType": "uint32"
              },
              {
                "name": "paused",
                "type": "bool",
                "internalType": "bool"
              }
            ]
          }
        ],
        "stateMutability": "view"
      },
      {
        "type": "function",
        "name": "createAgentProfile",
        "inputs": [
          {
            "name": "profileId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "agentId",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "metadataURI",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "metadataDigest",
            "type": "bytes32",
            "internalType": "bytes32"
          }
        ],
        "outputs": [],
        "stateMutability": "nonpayable"
      },
      {
        "type": "function",
        "name": "createProfile",
        "inputs": [
          {
            "name": "profileId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "metadataURI",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "metadataDigest",
            "type": "bytes32",
            "internalType": "bytes32"
          }
        ],
        "outputs": [],
        "stateMutability": "nonpayable"
      },
      {
        "type": "function",
        "name": "delegates",
        "inputs": [
          {
            "name": "profileId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "delegate",
            "type": "address",
            "internalType": "address"
          }
        ],
        "outputs": [
          {
            "name": "allowed",
            "type": "bool",
            "internalType": "bool"
          }
        ],
        "stateMutability": "view"
      },
      {
        "type": "function",
        "name": "identityRegistry",
        "inputs": [],
        "outputs": [
          {
            "name": "",
            "type": "address",
            "internalType": "contract IERC8004IdentityRegistry"
          }
        ],
        "stateMutability": "view"
      },
      {
        "type": "function",
        "name": "isAuthorized",
        "inputs": [
          {
            "name": "profileId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "actor",
            "type": "address",
            "internalType": "address"
          }
        ],
        "outputs": [
          {
            "name": "",
            "type": "bool",
            "internalType": "bool"
          }
        ],
        "stateMutability": "view"
      },
      {
        "type": "function",
        "name": "owner",
        "inputs": [],
        "outputs": [
          {
            "name": "",
            "type": "address",
            "internalType": "address"
          }
        ],
        "stateMutability": "view"
      },
      {
        "type": "function",
        "name": "pause",
        "inputs": [],
        "outputs": [],
        "stateMutability": "nonpayable"
      },
      {
        "type": "function",
        "name": "pausePolicy",
        "inputs": [
          {
            "name": "agentId",
            "type": "uint256",
            "internalType": "uint256"
          }
        ],
        "outputs": [],
        "stateMutability": "nonpayable"
      },
      {
        "type": "function",
        "name": "paused",
        "inputs": [],
        "outputs": [
          {
            "name": "",
            "type": "bool",
            "internalType": "bool"
          }
        ],
        "stateMutability": "view"
      },
      {
        "type": "function",
        "name": "profile",
        "inputs": [
          {
            "name": "profileId",
            "type": "bytes32",
            "internalType": "bytes32"
          }
        ],
        "outputs": [
          {
            "name": "",
            "type": "tuple",
            "internalType": "struct AttestiaProfileRegistry.Profile",
            "components": [
              {
                "name": "ownerSnapshot",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "metadataDigest",
                "type": "bytes32",
                "internalType": "bytes32"
              },
              {
                "name": "metadataURI",
                "type": "string",
                "internalType": "string"
              },
              {
                "name": "createdAt",
                "type": "uint64",
                "internalType": "uint64"
              },
              {
                "name": "updatedAt",
                "type": "uint64",
                "internalType": "uint64"
              },
              {
                "name": "agentId",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "isAgent",
                "type": "bool",
                "internalType": "bool"
              }
            ]
          }
        ],
        "stateMutability": "view"
      },
      {
        "type": "function",
        "name": "profileByAgent",
        "inputs": [
          {
            "name": "agentId",
            "type": "uint256",
            "internalType": "uint256"
          }
        ],
        "outputs": [
          {
            "name": "profileId",
            "type": "bytes32",
            "internalType": "bytes32"
          }
        ],
        "stateMutability": "view"
      },
      {
        "type": "function",
        "name": "profileExists",
        "inputs": [
          {
            "name": "profileId",
            "type": "bytes32",
            "internalType": "bytes32"
          }
        ],
        "outputs": [
          {
            "name": "",
            "type": "bool",
            "internalType": "bool"
          }
        ],
        "stateMutability": "view"
      },
      {
        "type": "function",
        "name": "renounceOwnership",
        "inputs": [],
        "outputs": [],
        "stateMutability": "nonpayable"
      },
      {
        "type": "function",
        "name": "setAgentPolicy",
        "inputs": [
          {
            "name": "agentId",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "policyDigest",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "policyURI",
            "type": "string",
            "internalType": "string"
          }
        ],
        "outputs": [],
        "stateMutability": "nonpayable"
      },
      {
        "type": "function",
        "name": "setDelegate",
        "inputs": [
          {
            "name": "profileId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "delegate",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "allowed",
            "type": "bool",
            "internalType": "bool"
          }
        ],
        "outputs": [],
        "stateMutability": "nonpayable"
      },
      {
        "type": "function",
        "name": "transferOwnership",
        "inputs": [
          {
            "name": "newOwner",
            "type": "address",
            "internalType": "address"
          }
        ],
        "outputs": [],
        "stateMutability": "nonpayable"
      },
      {
        "type": "function",
        "name": "unpause",
        "inputs": [],
        "outputs": [],
        "stateMutability": "nonpayable"
      },
      {
        "type": "function",
        "name": "updateProfile",
        "inputs": [
          {
            "name": "profileId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "metadataURI",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "metadataDigest",
            "type": "bytes32",
            "internalType": "bytes32"
          }
        ],
        "outputs": [],
        "stateMutability": "nonpayable"
      },
      {
        "type": "event",
        "name": "AgentPolicyPaused",
        "inputs": [
          {
            "name": "profileId",
            "type": "bytes32",
            "indexed": true,
            "internalType": "bytes32"
          },
          {
            "name": "agentId",
            "type": "uint256",
            "indexed": true,
            "internalType": "uint256"
          },
          {
            "name": "version",
            "type": "uint32",
            "indexed": false,
            "internalType": "uint32"
          },
          {
            "name": "actor",
            "type": "address",
            "indexed": true,
            "internalType": "address"
          },
          {
            "name": "pausedAt",
            "type": "uint64",
            "indexed": false,
            "internalType": "uint64"
          }
        ],
        "anonymous": false
      },
      {
        "type": "event",
        "name": "AgentPolicyUpdated",
        "inputs": [
          {
            "name": "profileId",
            "type": "bytes32",
            "indexed": true,
            "internalType": "bytes32"
          },
          {
            "name": "agentId",
            "type": "uint256",
            "indexed": true,
            "internalType": "uint256"
          },
          {
            "name": "version",
            "type": "uint32",
            "indexed": false,
            "internalType": "uint32"
          },
          {
            "name": "policyDigest",
            "type": "bytes32",
            "indexed": false,
            "internalType": "bytes32"
          },
          {
            "name": "policyURI",
            "type": "string",
            "indexed": false,
            "internalType": "string"
          },
          {
            "name": "actor",
            "type": "address",
            "indexed": true,
            "internalType": "address"
          },
          {
            "name": "updatedAt",
            "type": "uint64",
            "indexed": false,
            "internalType": "uint64"
          }
        ],
        "anonymous": false
      },
      {
        "type": "event",
        "name": "AgentProfileCreated",
        "inputs": [
          {
            "name": "profileId",
            "type": "bytes32",
            "indexed": true,
            "internalType": "bytes32"
          },
          {
            "name": "agentId",
            "type": "uint256",
            "indexed": true,
            "internalType": "uint256"
          },
          {
            "name": "owner",
            "type": "address",
            "indexed": true,
            "internalType": "address"
          },
          {
            "name": "identityRegistry",
            "type": "address",
            "indexed": false,
            "internalType": "address"
          },
          {
            "name": "metadataDigest",
            "type": "bytes32",
            "indexed": false,
            "internalType": "bytes32"
          },
          {
            "name": "metadataURI",
            "type": "string",
            "indexed": false,
            "internalType": "string"
          },
          {
            "name": "createdAt",
            "type": "uint64",
            "indexed": false,
            "internalType": "uint64"
          }
        ],
        "anonymous": false
      },
      {
        "type": "event",
        "name": "DelegateChanged",
        "inputs": [
          {
            "name": "profileId",
            "type": "bytes32",
            "indexed": true,
            "internalType": "bytes32"
          },
          {
            "name": "delegate",
            "type": "address",
            "indexed": true,
            "internalType": "address"
          },
          {
            "name": "allowed",
            "type": "bool",
            "indexed": false,
            "internalType": "bool"
          },
          {
            "name": "changedAt",
            "type": "uint64",
            "indexed": false,
            "internalType": "uint64"
          }
        ],
        "anonymous": false
      },
      {
        "type": "event",
        "name": "OwnershipTransferred",
        "inputs": [
          {
            "name": "previousOwner",
            "type": "address",
            "indexed": true,
            "internalType": "address"
          },
          {
            "name": "newOwner",
            "type": "address",
            "indexed": true,
            "internalType": "address"
          }
        ],
        "anonymous": false
      },
      {
        "type": "event",
        "name": "Paused",
        "inputs": [
          {
            "name": "account",
            "type": "address",
            "indexed": false,
            "internalType": "address"
          }
        ],
        "anonymous": false
      },
      {
        "type": "event",
        "name": "ProfileCreated",
        "inputs": [
          {
            "name": "profileId",
            "type": "bytes32",
            "indexed": true,
            "internalType": "bytes32"
          },
          {
            "name": "owner",
            "type": "address",
            "indexed": true,
            "internalType": "address"
          },
          {
            "name": "metadataDigest",
            "type": "bytes32",
            "indexed": false,
            "internalType": "bytes32"
          },
          {
            "name": "metadataURI",
            "type": "string",
            "indexed": false,
            "internalType": "string"
          },
          {
            "name": "createdAt",
            "type": "uint64",
            "indexed": false,
            "internalType": "uint64"
          }
        ],
        "anonymous": false
      },
      {
        "type": "event",
        "name": "ProfileUpdated",
        "inputs": [
          {
            "name": "profileId",
            "type": "bytes32",
            "indexed": true,
            "internalType": "bytes32"
          },
          {
            "name": "actor",
            "type": "address",
            "indexed": true,
            "internalType": "address"
          },
          {
            "name": "metadataDigest",
            "type": "bytes32",
            "indexed": false,
            "internalType": "bytes32"
          },
          {
            "name": "metadataURI",
            "type": "string",
            "indexed": false,
            "internalType": "string"
          },
          {
            "name": "updatedAt",
            "type": "uint64",
            "indexed": false,
            "internalType": "uint64"
          }
        ],
        "anonymous": false
      },
      {
        "type": "event",
        "name": "Unpaused",
        "inputs": [
          {
            "name": "account",
            "type": "address",
            "indexed": false,
            "internalType": "address"
          }
        ],
        "anonymous": false
      },
      {
        "type": "error",
        "name": "AgentAlreadyLinked",
        "inputs": [
          {
            "name": "agentId",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "profileId",
            "type": "bytes32",
            "internalType": "bytes32"
          }
        ]
      },
      {
        "type": "error",
        "name": "AgentProfileRequired",
        "inputs": [
          {
            "name": "profileId",
            "type": "bytes32",
            "internalType": "bytes32"
          }
        ]
      },
      {
        "type": "error",
        "name": "DelegateUnchanged",
        "inputs": [
          {
            "name": "profileId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "delegate",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "allowed",
            "type": "bool",
            "internalType": "bool"
          }
        ]
      },
      {
        "type": "error",
        "name": "EnforcedPause",
        "inputs": []
      },
      {
        "type": "error",
        "name": "ExpectedPause",
        "inputs": []
      },
      {
        "type": "error",
        "name": "HumanProfileRequired",
        "inputs": [
          {
            "name": "profileId",
            "type": "bytes32",
            "internalType": "bytes32"
          }
        ]
      },
      {
        "type": "error",
        "name": "IdentityRegistryUnavailable",
        "inputs": [
          {
            "name": "agentId",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      },
      {
        "type": "error",
        "name": "InvalidDigest",
        "inputs": []
      },
      {
        "type": "error",
        "name": "InvalidId",
        "inputs": []
      },
      {
        "type": "error",
        "name": "InvalidURI",
        "inputs": []
      },
      {
        "type": "error",
        "name": "OwnableInvalidOwner",
        "inputs": [
          {
            "name": "owner",
            "type": "address",
            "internalType": "address"
          }
        ]
      },
      {
        "type": "error",
        "name": "OwnableUnauthorizedAccount",
        "inputs": [
          {
            "name": "account",
            "type": "address",
            "internalType": "address"
          }
        ]
      },
      {
        "type": "error",
        "name": "PolicyAlreadyPaused",
        "inputs": [
          {
            "name": "agentId",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      },
      {
        "type": "error",
        "name": "PolicyNotFound",
        "inputs": [
          {
            "name": "agentId",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      },
      {
        "type": "error",
        "name": "ProfileAlreadyExists",
        "inputs": [
          {
            "name": "profileId",
            "type": "bytes32",
            "internalType": "bytes32"
          }
        ]
      },
      {
        "type": "error",
        "name": "ProfileNotFound",
        "inputs": [
          {
            "name": "profileId",
            "type": "bytes32",
            "internalType": "bytes32"
          }
        ]
      },
      {
        "type": "error",
        "name": "Unauthorized",
        "inputs": [
          {
            "name": "profileId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "actor",
            "type": "address",
            "internalType": "address"
          }
        ]
      },
      {
        "type": "error",
        "name": "ZeroAddress",
        "inputs": []
      }
    ]
  },
  "ContributionRegistry": {
    "address": "0x7BFB7e4A6325FC7Dd9141A13039B978852AF6c65",
    "abi": [
      {
        "type": "constructor",
        "inputs": [
          {
            "name": "initialOwner",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "profileRegistry_",
            "type": "address",
            "internalType": "address"
          }
        ],
        "stateMutability": "nonpayable"
      },
      {
        "type": "function",
        "name": "MAX_URI_LENGTH",
        "inputs": [],
        "outputs": [
          {
            "name": "",
            "type": "uint256",
            "internalType": "uint256"
          }
        ],
        "stateMutability": "view"
      },
      {
        "type": "function",
        "name": "archiveContribution",
        "inputs": [
          {
            "name": "contributionId",
            "type": "bytes32",
            "internalType": "bytes32"
          }
        ],
        "outputs": [],
        "stateMutability": "nonpayable"
      },
      {
        "type": "function",
        "name": "contribution",
        "inputs": [
          {
            "name": "contributionId",
            "type": "bytes32",
            "internalType": "bytes32"
          }
        ],
        "outputs": [
          {
            "name": "",
            "type": "tuple",
            "internalType": "struct ContributionRegistry.Contribution",
            "components": [
              {
                "name": "creatorProfileId",
                "type": "bytes32",
                "internalType": "bytes32"
              },
              {
                "name": "artifactDigest",
                "type": "bytes32",
                "internalType": "bytes32"
              },
              {
                "name": "metadataDigest",
                "type": "bytes32",
                "internalType": "bytes32"
              },
              {
                "name": "metadataURI",
                "type": "string",
                "internalType": "string"
              },
              {
                "name": "parentId",
                "type": "bytes32",
                "internalType": "bytes32"
              },
              {
                "name": "registeredBy",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "createdAt",
                "type": "uint64",
                "internalType": "uint64"
              },
              {
                "name": "archivedAt",
                "type": "uint64",
                "internalType": "uint64"
              }
            ]
          }
        ],
        "stateMutability": "view"
      },
      {
        "type": "function",
        "name": "contributionByRecordKey",
        "inputs": [
          {
            "name": "recordKey",
            "type": "bytes32",
            "internalType": "bytes32"
          }
        ],
        "outputs": [
          {
            "name": "contributionId",
            "type": "bytes32",
            "internalType": "bytes32"
          }
        ],
        "stateMutability": "view"
      },
      {
        "type": "function",
        "name": "contributionExists",
        "inputs": [
          {
            "name": "contributionId",
            "type": "bytes32",
            "internalType": "bytes32"
          }
        ],
        "outputs": [
          {
            "name": "",
            "type": "bool",
            "internalType": "bool"
          }
        ],
        "stateMutability": "view"
      },
      {
        "type": "function",
        "name": "creatorProfileOf",
        "inputs": [
          {
            "name": "contributionId",
            "type": "bytes32",
            "internalType": "bytes32"
          }
        ],
        "outputs": [
          {
            "name": "",
            "type": "bytes32",
            "internalType": "bytes32"
          }
        ],
        "stateMutability": "view"
      },
      {
        "type": "function",
        "name": "firstContributionByArtifact",
        "inputs": [
          {
            "name": "creatorProfileId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "artifactDigest",
            "type": "bytes32",
            "internalType": "bytes32"
          }
        ],
        "outputs": [
          {
            "name": "contributionId",
            "type": "bytes32",
            "internalType": "bytes32"
          }
        ],
        "stateMutability": "view"
      },
      {
        "type": "function",
        "name": "owner",
        "inputs": [],
        "outputs": [
          {
            "name": "",
            "type": "address",
            "internalType": "address"
          }
        ],
        "stateMutability": "view"
      },
      {
        "type": "function",
        "name": "pause",
        "inputs": [],
        "outputs": [],
        "stateMutability": "nonpayable"
      },
      {
        "type": "function",
        "name": "paused",
        "inputs": [],
        "outputs": [
          {
            "name": "",
            "type": "bool",
            "internalType": "bool"
          }
        ],
        "stateMutability": "view"
      },
      {
        "type": "function",
        "name": "profileRegistry",
        "inputs": [],
        "outputs": [
          {
            "name": "",
            "type": "address",
            "internalType": "contract IAttestiaProfileRegistry"
          }
        ],
        "stateMutability": "view"
      },
      {
        "type": "function",
        "name": "registerContribution",
        "inputs": [
          {
            "name": "contributionId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "creatorProfileId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "artifactDigest",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "metadataDigest",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "metadataURI",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "parentId",
            "type": "bytes32",
            "internalType": "bytes32"
          }
        ],
        "outputs": [],
        "stateMutability": "nonpayable"
      },
      {
        "type": "function",
        "name": "renounceOwnership",
        "inputs": [],
        "outputs": [],
        "stateMutability": "nonpayable"
      },
      {
        "type": "function",
        "name": "transferOwnership",
        "inputs": [
          {
            "name": "newOwner",
            "type": "address",
            "internalType": "address"
          }
        ],
        "outputs": [],
        "stateMutability": "nonpayable"
      },
      {
        "type": "function",
        "name": "unpause",
        "inputs": [],
        "outputs": [],
        "stateMutability": "nonpayable"
      },
      {
        "type": "event",
        "name": "ContributionArchived",
        "inputs": [
          {
            "name": "contributionId",
            "type": "bytes32",
            "indexed": true,
            "internalType": "bytes32"
          },
          {
            "name": "creatorProfileId",
            "type": "bytes32",
            "indexed": true,
            "internalType": "bytes32"
          },
          {
            "name": "actor",
            "type": "address",
            "indexed": true,
            "internalType": "address"
          },
          {
            "name": "archivedAt",
            "type": "uint64",
            "indexed": false,
            "internalType": "uint64"
          }
        ],
        "anonymous": false
      },
      {
        "type": "event",
        "name": "ContributionRegistered",
        "inputs": [
          {
            "name": "contributionId",
            "type": "bytes32",
            "indexed": true,
            "internalType": "bytes32"
          },
          {
            "name": "creatorProfileId",
            "type": "bytes32",
            "indexed": true,
            "internalType": "bytes32"
          },
          {
            "name": "artifactDigest",
            "type": "bytes32",
            "indexed": false,
            "internalType": "bytes32"
          },
          {
            "name": "metadataDigest",
            "type": "bytes32",
            "indexed": false,
            "internalType": "bytes32"
          },
          {
            "name": "metadataURI",
            "type": "string",
            "indexed": false,
            "internalType": "string"
          },
          {
            "name": "parentId",
            "type": "bytes32",
            "indexed": true,
            "internalType": "bytes32"
          },
          {
            "name": "registeredBy",
            "type": "address",
            "indexed": false,
            "internalType": "address"
          },
          {
            "name": "createdAt",
            "type": "uint64",
            "indexed": false,
            "internalType": "uint64"
          }
        ],
        "anonymous": false
      },
      {
        "type": "event",
        "name": "OwnershipTransferred",
        "inputs": [
          {
            "name": "previousOwner",
            "type": "address",
            "indexed": true,
            "internalType": "address"
          },
          {
            "name": "newOwner",
            "type": "address",
            "indexed": true,
            "internalType": "address"
          }
        ],
        "anonymous": false
      },
      {
        "type": "event",
        "name": "Paused",
        "inputs": [
          {
            "name": "account",
            "type": "address",
            "indexed": false,
            "internalType": "address"
          }
        ],
        "anonymous": false
      },
      {
        "type": "event",
        "name": "Unpaused",
        "inputs": [
          {
            "name": "account",
            "type": "address",
            "indexed": false,
            "internalType": "address"
          }
        ],
        "anonymous": false
      },
      {
        "type": "error",
        "name": "AlreadyArchived",
        "inputs": [
          {
            "name": "contributionId",
            "type": "bytes32",
            "internalType": "bytes32"
          }
        ]
      },
      {
        "type": "error",
        "name": "ContributionAlreadyExists",
        "inputs": [
          {
            "name": "contributionId",
            "type": "bytes32",
            "internalType": "bytes32"
          }
        ]
      },
      {
        "type": "error",
        "name": "ContributionNotFound",
        "inputs": [
          {
            "name": "contributionId",
            "type": "bytes32",
            "internalType": "bytes32"
          }
        ]
      },
      {
        "type": "error",
        "name": "DuplicateArtifact",
        "inputs": [
          {
            "name": "existingContributionId",
            "type": "bytes32",
            "internalType": "bytes32"
          }
        ]
      },
      {
        "type": "error",
        "name": "DuplicateRecord",
        "inputs": [
          {
            "name": "existingContributionId",
            "type": "bytes32",
            "internalType": "bytes32"
          }
        ]
      },
      {
        "type": "error",
        "name": "EnforcedPause",
        "inputs": []
      },
      {
        "type": "error",
        "name": "ExpectedPause",
        "inputs": []
      },
      {
        "type": "error",
        "name": "InvalidDigest",
        "inputs": []
      },
      {
        "type": "error",
        "name": "InvalidId",
        "inputs": []
      },
      {
        "type": "error",
        "name": "InvalidURI",
        "inputs": []
      },
      {
        "type": "error",
        "name": "MetadataUnchanged",
        "inputs": [
          {
            "name": "parentId",
            "type": "bytes32",
            "internalType": "bytes32"
          }
        ]
      },
      {
        "type": "error",
        "name": "OwnableInvalidOwner",
        "inputs": [
          {
            "name": "owner",
            "type": "address",
            "internalType": "address"
          }
        ]
      },
      {
        "type": "error",
        "name": "OwnableUnauthorizedAccount",
        "inputs": [
          {
            "name": "account",
            "type": "address",
            "internalType": "address"
          }
        ]
      },
      {
        "type": "error",
        "name": "ParentCreatorMismatch",
        "inputs": [
          {
            "name": "parentId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "creatorProfileId",
            "type": "bytes32",
            "internalType": "bytes32"
          }
        ]
      },
      {
        "type": "error",
        "name": "ProfileNotFound",
        "inputs": [
          {
            "name": "profileId",
            "type": "bytes32",
            "internalType": "bytes32"
          }
        ]
      },
      {
        "type": "error",
        "name": "Unauthorized",
        "inputs": [
          {
            "name": "profileId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "actor",
            "type": "address",
            "internalType": "address"
          }
        ]
      },
      {
        "type": "error",
        "name": "ZeroAddress",
        "inputs": []
      }
    ]
  },
  "AttestationRegistry": {
    "address": "0xa948F485d0ddEb514402B046B3707Dfc16830b71",
    "abi": [
      {
        "type": "constructor",
        "inputs": [
          {
            "name": "initialOwner",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "profileRegistry_",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "contributionRegistry_",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "negativeClaimsEnabled_",
            "type": "bool",
            "internalType": "bool"
          }
        ],
        "stateMutability": "nonpayable"
      },
      {
        "type": "function",
        "name": "AUTHORSHIP",
        "inputs": [],
        "outputs": [
          {
            "name": "",
            "type": "bytes32",
            "internalType": "bytes32"
          }
        ],
        "stateMutability": "view"
      },
      {
        "type": "function",
        "name": "COMPLETION",
        "inputs": [],
        "outputs": [
          {
            "name": "",
            "type": "bytes32",
            "internalType": "bytes32"
          }
        ],
        "stateMutability": "view"
      },
      {
        "type": "function",
        "name": "MAX_URI_LENGTH",
        "inputs": [],
        "outputs": [
          {
            "name": "",
            "type": "uint256",
            "internalType": "uint256"
          }
        ],
        "stateMutability": "view"
      },
      {
        "type": "function",
        "name": "PROVENANCE",
        "inputs": [],
        "outputs": [
          {
            "name": "",
            "type": "bytes32",
            "internalType": "bytes32"
          }
        ],
        "stateMutability": "view"
      },
      {
        "type": "function",
        "name": "QUALITY",
        "inputs": [],
        "outputs": [
          {
            "name": "",
            "type": "bytes32",
            "internalType": "bytes32"
          }
        ],
        "stateMutability": "view"
      },
      {
        "type": "function",
        "name": "USAGE",
        "inputs": [],
        "outputs": [
          {
            "name": "",
            "type": "bytes32",
            "internalType": "bytes32"
          }
        ],
        "stateMutability": "view"
      },
      {
        "type": "function",
        "name": "attest",
        "inputs": [
          {
            "name": "attestationId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "contributionId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "claimType",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "result",
            "type": "int8",
            "internalType": "int8"
          },
          {
            "name": "workspaceId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "rubricId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "rubricVersion",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "rubricDigest",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "metadataDigest",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "metadataURI",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "evidenceDigest",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "evidenceURI",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "validUntil",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "supersedes",
            "type": "bytes32",
            "internalType": "bytes32"
          }
        ],
        "outputs": [],
        "stateMutability": "nonpayable"
      },
      {
        "type": "function",
        "name": "attestation",
        "inputs": [
          {
            "name": "attestationId",
            "type": "bytes32",
            "internalType": "bytes32"
          }
        ],
        "outputs": [
          {
            "name": "",
            "type": "tuple",
            "internalType": "struct AttestationRegistry.Attestation",
            "components": [
              {
                "name": "contributionId",
                "type": "bytes32",
                "internalType": "bytes32"
              },
              {
                "name": "claimType",
                "type": "bytes32",
                "internalType": "bytes32"
              },
              {
                "name": "result",
                "type": "int8",
                "internalType": "int8"
              },
              {
                "name": "issuer",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "workspaceId",
                "type": "bytes32",
                "internalType": "bytes32"
              },
              {
                "name": "rubricId",
                "type": "bytes32",
                "internalType": "bytes32"
              },
              {
                "name": "rubricVersion",
                "type": "uint32",
                "internalType": "uint32"
              },
              {
                "name": "rubricDigest",
                "type": "bytes32",
                "internalType": "bytes32"
              },
              {
                "name": "metadataDigest",
                "type": "bytes32",
                "internalType": "bytes32"
              },
              {
                "name": "metadataURI",
                "type": "string",
                "internalType": "string"
              },
              {
                "name": "evidenceDigest",
                "type": "bytes32",
                "internalType": "bytes32"
              },
              {
                "name": "evidenceURI",
                "type": "string",
                "internalType": "string"
              },
              {
                "name": "issuedAt",
                "type": "uint64",
                "internalType": "uint64"
              },
              {
                "name": "validUntil",
                "type": "uint64",
                "internalType": "uint64"
              },
              {
                "name": "supersedes",
                "type": "bytes32",
                "internalType": "bytes32"
              },
              {
                "name": "supersededBy",
                "type": "bytes32",
                "internalType": "bytes32"
              },
              {
                "name": "revokedAt",
                "type": "uint64",
                "internalType": "uint64"
              },
              {
                "name": "revocationReasonDigest",
                "type": "bytes32",
                "internalType": "bytes32"
              },
              {
                "name": "revocationReasonURI",
                "type": "string",
                "internalType": "string"
              },
              {
                "name": "selfAtIssuance",
                "type": "bool",
                "internalType": "bool"
              }
            ]
          }
        ],
        "stateMutability": "view"
      },
      {
        "type": "function",
        "name": "claimKey",
        "inputs": [
          {
            "name": "issuer",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "contributionId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "claimType",
            "type": "bytes32",
            "internalType": "bytes32"
          }
        ],
        "outputs": [
          {
            "name": "",
            "type": "bytes32",
            "internalType": "bytes32"
          }
        ],
        "stateMutability": "pure"
      },
      {
        "type": "function",
        "name": "contributionRegistry",
        "inputs": [],
        "outputs": [
          {
            "name": "",
            "type": "address",
            "internalType": "contract IContributionRegistry"
          }
        ],
        "stateMutability": "view"
      },
      {
        "type": "function",
        "name": "currentAttestation",
        "inputs": [
          {
            "name": "claimKey",
            "type": "bytes32",
            "internalType": "bytes32"
          }
        ],
        "outputs": [
          {
            "name": "attestationId",
            "type": "bytes32",
            "internalType": "bytes32"
          }
        ],
        "stateMutability": "view"
      },
      {
        "type": "function",
        "name": "isActive",
        "inputs": [
          {
            "name": "attestationId",
            "type": "bytes32",
            "internalType": "bytes32"
          }
        ],
        "outputs": [
          {
            "name": "",
            "type": "bool",
            "internalType": "bool"
          }
        ],
        "stateMutability": "view"
      },
      {
        "type": "function",
        "name": "negativeClaimsEnabled",
        "inputs": [],
        "outputs": [
          {
            "name": "",
            "type": "bool",
            "internalType": "bool"
          }
        ],
        "stateMutability": "view"
      },
      {
        "type": "function",
        "name": "owner",
        "inputs": [],
        "outputs": [
          {
            "name": "",
            "type": "address",
            "internalType": "address"
          }
        ],
        "stateMutability": "view"
      },
      {
        "type": "function",
        "name": "pause",
        "inputs": [],
        "outputs": [],
        "stateMutability": "nonpayable"
      },
      {
        "type": "function",
        "name": "paused",
        "inputs": [],
        "outputs": [
          {
            "name": "",
            "type": "bool",
            "internalType": "bool"
          }
        ],
        "stateMutability": "view"
      },
      {
        "type": "function",
        "name": "profileRegistry",
        "inputs": [],
        "outputs": [
          {
            "name": "",
            "type": "address",
            "internalType": "contract IAttestiaProfileRegistry"
          }
        ],
        "stateMutability": "view"
      },
      {
        "type": "function",
        "name": "renounceOwnership",
        "inputs": [],
        "outputs": [],
        "stateMutability": "nonpayable"
      },
      {
        "type": "function",
        "name": "revoke",
        "inputs": [
          {
            "name": "attestationId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "reasonDigest",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "reasonURI",
            "type": "string",
            "internalType": "string"
          }
        ],
        "outputs": [],
        "stateMutability": "nonpayable"
      },
      {
        "type": "function",
        "name": "transferOwnership",
        "inputs": [
          {
            "name": "newOwner",
            "type": "address",
            "internalType": "address"
          }
        ],
        "outputs": [],
        "stateMutability": "nonpayable"
      },
      {
        "type": "function",
        "name": "unpause",
        "inputs": [],
        "outputs": [],
        "stateMutability": "nonpayable"
      },
      {
        "type": "event",
        "name": "AttestationCreated",
        "inputs": [
          {
            "name": "attestationId",
            "type": "bytes32",
            "indexed": true,
            "internalType": "bytes32"
          },
          {
            "name": "contributionId",
            "type": "bytes32",
            "indexed": true,
            "internalType": "bytes32"
          },
          {
            "name": "issuer",
            "type": "address",
            "indexed": true,
            "internalType": "address"
          },
          {
            "name": "claimType",
            "type": "bytes32",
            "indexed": false,
            "internalType": "bytes32"
          },
          {
            "name": "result",
            "type": "int8",
            "indexed": false,
            "internalType": "int8"
          },
          {
            "name": "workspaceId",
            "type": "bytes32",
            "indexed": false,
            "internalType": "bytes32"
          },
          {
            "name": "rubricId",
            "type": "bytes32",
            "indexed": false,
            "internalType": "bytes32"
          },
          {
            "name": "rubricVersion",
            "type": "uint32",
            "indexed": false,
            "internalType": "uint32"
          },
          {
            "name": "rubricDigest",
            "type": "bytes32",
            "indexed": false,
            "internalType": "bytes32"
          },
          {
            "name": "metadataDigest",
            "type": "bytes32",
            "indexed": false,
            "internalType": "bytes32"
          },
          {
            "name": "metadataURI",
            "type": "string",
            "indexed": false,
            "internalType": "string"
          },
          {
            "name": "evidenceDigest",
            "type": "bytes32",
            "indexed": false,
            "internalType": "bytes32"
          },
          {
            "name": "evidenceURI",
            "type": "string",
            "indexed": false,
            "internalType": "string"
          },
          {
            "name": "issuedAt",
            "type": "uint64",
            "indexed": false,
            "internalType": "uint64"
          },
          {
            "name": "validUntil",
            "type": "uint64",
            "indexed": false,
            "internalType": "uint64"
          },
          {
            "name": "supersedes",
            "type": "bytes32",
            "indexed": false,
            "internalType": "bytes32"
          },
          {
            "name": "selfAtIssuance",
            "type": "bool",
            "indexed": false,
            "internalType": "bool"
          }
        ],
        "anonymous": false
      },
      {
        "type": "event",
        "name": "AttestationRevoked",
        "inputs": [
          {
            "name": "attestationId",
            "type": "bytes32",
            "indexed": true,
            "internalType": "bytes32"
          },
          {
            "name": "issuer",
            "type": "address",
            "indexed": true,
            "internalType": "address"
          },
          {
            "name": "revokedAt",
            "type": "uint64",
            "indexed": false,
            "internalType": "uint64"
          },
          {
            "name": "reasonDigest",
            "type": "bytes32",
            "indexed": false,
            "internalType": "bytes32"
          },
          {
            "name": "reasonURI",
            "type": "string",
            "indexed": false,
            "internalType": "string"
          }
        ],
        "anonymous": false
      },
      {
        "type": "event",
        "name": "AttestationSuperseded",
        "inputs": [
          {
            "name": "oldAttestationId",
            "type": "bytes32",
            "indexed": true,
            "internalType": "bytes32"
          },
          {
            "name": "newAttestationId",
            "type": "bytes32",
            "indexed": true,
            "internalType": "bytes32"
          },
          {
            "name": "issuer",
            "type": "address",
            "indexed": true,
            "internalType": "address"
          },
          {
            "name": "supersededAt",
            "type": "uint64",
            "indexed": false,
            "internalType": "uint64"
          }
        ],
        "anonymous": false
      },
      {
        "type": "event",
        "name": "OwnershipTransferred",
        "inputs": [
          {
            "name": "previousOwner",
            "type": "address",
            "indexed": true,
            "internalType": "address"
          },
          {
            "name": "newOwner",
            "type": "address",
            "indexed": true,
            "internalType": "address"
          }
        ],
        "anonymous": false
      },
      {
        "type": "event",
        "name": "Paused",
        "inputs": [
          {
            "name": "account",
            "type": "address",
            "indexed": false,
            "internalType": "address"
          }
        ],
        "anonymous": false
      },
      {
        "type": "event",
        "name": "Unpaused",
        "inputs": [
          {
            "name": "account",
            "type": "address",
            "indexed": false,
            "internalType": "address"
          }
        ],
        "anonymous": false
      },
      {
        "type": "error",
        "name": "ActiveClaimExists",
        "inputs": [
          {
            "name": "currentAttestationId",
            "type": "bytes32",
            "internalType": "bytes32"
          }
        ]
      },
      {
        "type": "error",
        "name": "AlreadyRevoked",
        "inputs": [
          {
            "name": "attestationId",
            "type": "bytes32",
            "internalType": "bytes32"
          }
        ]
      },
      {
        "type": "error",
        "name": "AttestationAlreadyExists",
        "inputs": [
          {
            "name": "attestationId",
            "type": "bytes32",
            "internalType": "bytes32"
          }
        ]
      },
      {
        "type": "error",
        "name": "AttestationNotFound",
        "inputs": [
          {
            "name": "attestationId",
            "type": "bytes32",
            "internalType": "bytes32"
          }
        ]
      },
      {
        "type": "error",
        "name": "ContributionNotFound",
        "inputs": [
          {
            "name": "contributionId",
            "type": "bytes32",
            "internalType": "bytes32"
          }
        ]
      },
      {
        "type": "error",
        "name": "EnforcedPause",
        "inputs": []
      },
      {
        "type": "error",
        "name": "ExpectedPause",
        "inputs": []
      },
      {
        "type": "error",
        "name": "InvalidClaimType",
        "inputs": [
          {
            "name": "claimType",
            "type": "bytes32",
            "internalType": "bytes32"
          }
        ]
      },
      {
        "type": "error",
        "name": "InvalidDigest",
        "inputs": []
      },
      {
        "type": "error",
        "name": "InvalidEvidence",
        "inputs": []
      },
      {
        "type": "error",
        "name": "InvalidExpiry",
        "inputs": [
          {
            "name": "validUntil",
            "type": "uint64",
            "internalType": "uint64"
          }
        ]
      },
      {
        "type": "error",
        "name": "InvalidId",
        "inputs": []
      },
      {
        "type": "error",
        "name": "InvalidResult",
        "inputs": [
          {
            "name": "result",
            "type": "int8",
            "internalType": "int8"
          }
        ]
      },
      {
        "type": "error",
        "name": "InvalidRubricBinding",
        "inputs": []
      },
      {
        "type": "error",
        "name": "InvalidSupersession",
        "inputs": [
          {
            "name": "supplied",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "expected",
            "type": "bytes32",
            "internalType": "bytes32"
          }
        ]
      },
      {
        "type": "error",
        "name": "InvalidURI",
        "inputs": []
      },
      {
        "type": "error",
        "name": "NegativeClaimsDisabled",
        "inputs": []
      },
      {
        "type": "error",
        "name": "OwnableInvalidOwner",
        "inputs": [
          {
            "name": "owner",
            "type": "address",
            "internalType": "address"
          }
        ]
      },
      {
        "type": "error",
        "name": "OwnableUnauthorizedAccount",
        "inputs": [
          {
            "name": "account",
            "type": "address",
            "internalType": "address"
          }
        ]
      },
      {
        "type": "error",
        "name": "UnauthorizedRevocation",
        "inputs": [
          {
            "name": "attestationId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "actor",
            "type": "address",
            "internalType": "address"
          }
        ]
      },
      {
        "type": "error",
        "name": "UnexpectedRubricBinding",
        "inputs": []
      },
      {
        "type": "error",
        "name": "ZeroAddress",
        "inputs": []
      }
    ]
  }
} as const;
