import { AgentActions } from "@/components/agent-actions";
import { explorer } from "@/lib/chain";
import { readAgent } from "@/lib/agent";
const ZERO = `0x${"0".repeat(64)}`;
export default async function AgentPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params; let agent: Awaited<ReturnType<typeof readAgent>> | null = null; try { if (/^\d+$/.test(id)) agent = await readAgent(BigInt(id)); } catch {}
  if (!agent) return <div className="page narrow"><section className="panel form-panel"><span className="badge" data-tone="danger">Unavailable</span><h1>Agent not found</h1><p>Check the ERC-8004 ID and Monad Testnet RPC.</p></section></div>;
  const metadata = agent.metadata ?? {}; const linked = agent.linkedProfileId.toLowerCase() !== ZERO;
  return <div className="page profile-page"><section className="panel profile-hero"><div><p className="eyebrow">ERC-8004 Identity Registry</p><h1 className="section-title">{String(metadata.name ?? `Agent #${id}`)}</h1><p className="lede">{String(metadata.description ?? "No public description supplied.")}</p></div><span className="badge" data-tone={metadata.active === false ? "danger" : "active"}>{metadata.active === false ? "Inactive" : "Registry active"}</span></section>
  <div className="grid-2"><section className="panel form-panel"><h2>Live identity</h2><dl className="review-list"><div><dt>Owner</dt><dd><a className="data" href={explorer.address(agent.owner)}>{agent.owner}</a></dd></div><div><dt>Agent wallet</dt><dd>{agent.agentWallet}</dd></div><div><dt>Agent URI</dt><dd>{agent.agentURI}</dd></div><div><dt>Attestia profile</dt><dd>{linked ? agent.linkedProfileId : "Not linked"}</dd></div></dl></section><section className="panel form-panel"><p className="eyebrow">Declared policy</p><h2>Version {agent.policy.version}</h2><span className="badge" data-tone={agent.policy.paused ? "danger" : agent.policy.version ? "active" : "pending"}>{agent.policy.paused ? "Paused" : agent.policy.version ? "Declared" : "Not published"}</span><p className="muted">A declaration describes intended behavior. It does not prove autonomous enforcement.</p>{agent.policy.version > 0 && <dl className="review-list"><div><dt>Digest</dt><dd>{agent.policy.digest}</dd></div><div><dt>URI</dt><dd>{agent.policy.uri}</dd></div></dl>}{agent.policyHistory.length > 0 && <details className="node-list"><summary>Version history</summary><ol>{agent.policyHistory.map((version) => <li key={version.version}>v{version.version} · {version.pausedAt ? "paused" : "published"} · <span className="data">{version.digest.slice(0, 14)}…</span></li>)}</ol></details>}</section></div>
  <section className="panel form-panel"><div className="section-heading"><div><p className="eyebrow">Separate trust source</p><h2>ERC-8004 feedback</h2></div><span className="badge">{agent.erc8004Feedback.length} records</span></div>{agent.erc8004Feedback.length ? <ul className="feedback-list">{agent.erc8004Feedback.map((item) => <li key={`${item.client}-${item.feedbackIndex}`}><span>{item.tag1 || "untagged"}{item.tag2 && ` · ${item.tag2}`}</span><strong className="data">{item.value}{item.valueDecimals ? ` × 10⁻${item.valueDecimals}` : ""}</strong><span className="muted">{item.revoked ? "revoked" : "active"}</span></li>)}</ul> : <p className="muted">No native ERC-8004 feedback. Attestia contribution claims are intentionally not merged into this count.</p>}</section>
  <AgentActions agentId={id} linked={linked} policyDigest={agent.policy.digest} policyPaused={agent.policy.paused} /></div>;
}
