"use client";
import { usePrivy, useWallets } from "@privy-io/react-auth";
import { useState } from "react";
import { encodeFunctionData, keccak256, stringToHex } from "viem";
import { advanceOperation, beginOperation, establishPrivySession, uploadPublicFile } from "@/lib/browser-wallet";
import { contracts } from "@/lib/contracts.generated";
import { canonicalJson, metadataDigest } from "@/lib/integrity";
import { useAttestiaWrite } from "@/lib/use-attestia-write";
import { track } from "@/lib/analytics";

export function AgentActions({ agentId, linked, policyDigest, policyPaused, owner }: { owner: string; agentId: string; linked: boolean; policyDigest: `0x${string}`; policyPaused: boolean }) {
  const { authenticated, login, getAccessToken } = usePrivy(); const { wallets } = useWallets(); const { writeContract } = useAttestiaWrite();
  const ownsAgent = wallets[0]?.address.toLowerCase() === owner.toLowerCase();
  const [reviewed, setReviewed] = useState(false);
  const [name, setName] = useState(""); const [capabilities, setCapabilities] = useState(""); const [approvals, setApprovals] = useState("Human approval before external writes"); const [status, setStatus] = useState("");
  async function session() { if (!authenticated) { login(); throw new Error("Sign in to continue"); } const wallet = wallets[0]; if (!ownsAgent) throw new Error("Switch to the ERC-8004 owner wallet before publishing"); if (!reviewed) throw new Error("Review public metadata before publishing"); const token = await getAccessToken(); if (!wallet || !token) throw new Error("Session expired"); await establishPrivySession(token, wallet.address); return wallet; }
  async function submit(kind: "create_agent_profile" | "set_agent_policy", payload: object, args: readonly unknown[], recordId: string) {
    const wallet = await session(); const digest = metadataDigest(payload); const upload = await uploadPublicFile(new File([canonicalJson(payload)], `${kind}.json`, { type: "application/json" })); const operation = await beginOperation(kind, wallet.address, digest, recordId); if (operation.transactionHash) { setStatus(`Already submitted ${operation.transactionHash}`); return; } await advanceOperation(operation.id, "awaiting_signature");
    const data = kind === "create_agent_profile" ? encodeFunctionData({ ...contracts.AttestiaProfileRegistry, functionName: "createAgentProfile", args: [...args, upload.uri, digest] as [`0x${string}`, bigint, string, `0x${string}`] }) : encodeFunctionData({ ...contracts.AttestiaProfileRegistry, functionName: "setAgentPolicy", args: [BigInt(agentId), digest, upload.uri] });
    const { hash } = await writeContract({ wallet, to: contracts.AttestiaProfileRegistry.address, data }); await advanceOperation(operation.id, "submitted", hash); setStatus(`Submitted ${hash}. Indexing may lag.`);
  }
  async function link() { try { const profileId = keccak256(stringToHex(`attestia:agent:10143:${agentId}`)); const metadata = { schema: "attestia.profile.v1", type: "agent", displayName: name, bio: "ERC-8004 linked agent", role: "Agent", skills: capabilities.split(",").map((v) => v.trim()).filter(Boolean), communities: [], agentLink: { chainId: 10143, agentId } }; await submit("create_agent_profile", metadata, [profileId, BigInt(agentId)], profileId); track("agent_registered", { chainId: 10143 }); } catch (error) { setStatus(error instanceof Error ? error.message : "Link failed"); } }
  async function publishPolicy(event: React.FormEvent) { event.preventDefault(); try { const policy = { schema: "attestia.agent-policy.v1", agentId, chainId: 10143, capabilities: capabilities.split(",").map((v) => v.trim()).filter(Boolean), approvals: approvals.split("\n").map((v) => v.trim()).filter(Boolean), enforcement: "declared", publishedAt: new Date().toISOString() }; await submit("set_agent_policy", policy, [], agentId); track("policy_published", { enforcement: "declared" }); } catch (error) { setStatus(error instanceof Error ? error.message : "Policy publication failed"); } }
  async function pausePolicy() { try { const wallet = await session(); const operation = await beginOperation("pause_agent_policy", wallet.address, policyDigest, agentId); if (operation.transactionHash) { setStatus(`Already submitted ${operation.transactionHash}`); return; } await advanceOperation(operation.id, "awaiting_signature"); const data = encodeFunctionData({ ...contracts.AttestiaProfileRegistry, functionName: "pausePolicy", args: [BigInt(agentId)] }); const { hash } = await writeContract({ wallet, to: contracts.AttestiaProfileRegistry.address, data }); await advanceOperation(operation.id, "submitted", hash); setStatus(`Pause submitted ${hash}`); } catch (error) { setStatus(error instanceof Error ? error.message : "Pause failed"); } }
  return <section className="panel form-panel"><p className="eyebrow">Owner actions</p><h2 className="section-title">{linked ? "Publish declared policy" : "Link this agent"}</h2><p className="muted">The registry checks live ERC-8004 ownership before accepting either transaction.</p><form className="stack composer-fields" onSubmit={linked ? publishPolicy : (event) => { event.preventDefault(); link(); }}><label className="field"><span>{linked ? "Capabilities, comma separated" : "Agent display name"}</span><input className="input" value={linked ? capabilities : name} onChange={(event) => linked ? setCapabilities(event.target.value) : setName(event.target.value)} required /></label>{linked && <label className="field"><span>Required approvals, one per line</span><textarea className="input" value={approvals} onChange={(event) => setApprovals(event.target.value)} required /></label>}<label className="field"><span><input type="checkbox" checked={reviewed} onChange={(event) => setReviewed(event.target.checked)} /> I reviewed this public metadata. It contains no private information or credentials.</span></label>{authenticated && !ownsAgent && <p role="status">Connected wallet is not the current ERC-8004 owner. Switch to the owner wallet to publish.</p>}<div className="cluster"><button className="pill pill-primary" disabled={authenticated && (!ownsAgent || !reviewed)}>{authenticated ? linked ? "Review and publish policy" : "Link agent profile" : "Sign in to continue"}</button>{linked && policyDigest !== `0x${"0".repeat(64)}` && !policyPaused && <button className="pill pill-secondary" type="button" onClick={pausePolicy}>Pause current policy</button>}</div>{status && <p className="operation-status" role="status">{status}</p>}</form></section>;
}
