"use client";
import { usePrivy, useWallets } from "@privy-io/react-auth";
import { useState } from "react";
import { encodeAbiParameters, keccak256, stringToHex } from "viem";
import { advanceOperation, beginOperation, establishPrivySession, monadWallet, uploadPublicFile } from "@/lib/browser-wallet";
import { contracts } from "@/lib/contracts.generated";
import { canonicalJson, metadataDigest, sha256, validatePublicUrl } from "@/lib/integrity";
import { claimTypes } from "@/lib/schemas";
import { track } from "@/lib/analytics";

const ZERO = `0x${"0".repeat(64)}` as `0x${string}`; const WORKSPACE = keccak256(stringToHex("attestia:public"));
function Actions({ contributionId }: { contributionId: `0x${string}` }) {
  const { authenticated, login, getAccessToken } = usePrivy(); const { wallets } = useWallets();
  const [claimType, setClaimType] = useState<(typeof claimTypes)[number]>("COMPLETION"); const [evidence, setEvidence] = useState(""); const [notes, setNotes] = useState(""); const [status, setStatus] = useState("");
  const [rubricId, setRubricId] = useState(""); const [rubricDigest, setRubricDigest] = useState(""); const [rubricUri, setRubricUri] = useState(""); const [rubricVersion, setRubricVersion] = useState(1); const [invitee, setInvitee] = useState("");
  async function session() { if (!authenticated) { login(); throw new Error("Sign in to continue; your input is preserved"); } const wallet = wallets[0]; const token = await getAccessToken(); if (!wallet || !token) throw new Error("Session expired; your input is preserved"); await establishPrivySession(token, wallet.address); return wallet; }
  async function attest(event: React.FormEvent) {
    event.preventDefault(); try {
      const wallet = await session(); validatePublicUrl(evidence); if (claimType === "USAGE" && !/^https:\/\/github\.com\/[^/]+\/[^/]+\/pull\/\d+/.test(evidence)) throw new Error("USAGE evidence must identify a GitHub pull request merge");
      if (claimType === "QUALITY" && (!/^0x[0-9a-fA-F]{64}$/.test(rubricId) || !/^0x[0-9a-fA-F]{64}$/.test(rubricDigest) || !rubricUri)) throw new Error("QUALITY requires a published rubric ID, digest, and URI");
      if (rubricUri) validatePublicUrl(rubricUri); const createdAt = new Date().toISOString(); const evidenceDigest = await sha256(new TextEncoder().encode(evidence));
      const assessment = claimType === "COMPLETION" ? { deliverable: notes, observedAt: createdAt } : claimType === "AUTHORSHIP" ? { contributionRole: "Contributor", basis: notes } : claimType === "QUALITY" ? { criterionResults: [{ criterionId: "overall", result: 1, notes }] } : claimType === "USAGE" ? { action: "merged", referenceUrl: evidence, observedAt: createdAt } : { reviewedAspects: ["human-input", "ai-disclosure", "sources"], notes };
      const metadata = { schema: `attestia.claim.${claimType.toLowerCase()}.v1`, contributionId, attester: wallet.address, claimType, result: 1, reason: null, createdAt, validUntil: 0, supersedes: null, workspaceId: WORKSPACE, evidence: { uri: evidence, sha256: evidenceDigest, mediaType: "text/uri-list", fileName: "public-source.url", byteLength: evidence.length }, rubric: claimType === "QUALITY" ? { id: rubricId, digest: rubricDigest, version: rubricVersion, uri: rubricUri } : null, conflictOfInterest: { hasConflict: false, disclosure: null }, assessment };
      setStatus("Publishing claim metadata…"); const upload = await uploadPublicFile(new File([canonicalJson(metadata)], "attestation.json", { type: "application/json" })); const digest = metadataDigest(metadata);
      const attestationId = keccak256(encodeAbiParameters([{ type: "address" }, { type: "bytes32" }, { type: "bytes32" }, { type: "bytes32" }], [wallet.address as `0x${string}`, contributionId, keccak256(stringToHex(claimType)), digest]));
      const operation = await beginOperation("create_attestation", wallet.address, digest, attestationId); if (operation.transactionHash) { setStatus(`Already submitted ${operation.transactionHash}`); return; }
      await advanceOperation(operation.id, "awaiting_signature"); setStatus("Awaiting reviewer signature…"); const client = await monadWallet(await wallet.getEthereumProvider(), wallet.address as `0x${string}`);
      const hash = await client.writeContract({ ...contracts.AttestationRegistry, functionName: "attest", args: [attestationId, contributionId, keccak256(stringToHex(claimType)), 1, claimType === "QUALITY" ? WORKSPACE : ZERO, claimType === "QUALITY" ? rubricId as `0x${string}` : ZERO, claimType === "QUALITY" ? rubricVersion : 0, claimType === "QUALITY" ? rubricDigest as `0x${string}` : ZERO, digest, upload.uri, evidenceDigest, evidence, 0n, ZERO] }); await advanceOperation(operation.id, "submitted", hash); track("reviewer_conversion", { claimType }); setStatus(`Submitted ${hash}. The indexer may lag behind finality.`);
    } catch (error) { setStatus(error instanceof Error ? error.message : "Attestation failed"); }
  }
  async function invite() { try { await session(); const response = await fetch("/api/invitations", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ contributionId, recipient: invitee }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error.message); setStatus(`Invitation prepared: ${body.id}`); } catch (error) { setStatus(error instanceof Error ? error.message : "Invitation failed"); } }
  return <div className="stack"><form className="panel form-panel" onSubmit={attest}><p className="eyebrow">Anyone may attest · Public evidence</p><h2 className="section-title">Issue a claim</h2><div className="stack composer-fields"><div className="field"><label htmlFor="claim">Claim type</label><select id="claim" className="input" value={claimType} onChange={(e) => setClaimType(e.target.value as typeof claimType)}>{claimTypes.map((value) => <option key={value}>{value}</option>)}</select></div><div className="field"><label htmlFor="evidence">Evidence URL{claimType === "USAGE" && " · GitHub merged PR"}</label><input id="evidence" className="input" type="url" value={evidence} onChange={(e) => setEvidence(e.target.value)} required /></div><div className="field"><label htmlFor="notes">Assessment</label><textarea id="notes" className="input" value={notes} onChange={(e) => setNotes(e.target.value)} required minLength={10} /></div>{claimType === "QUALITY" && <div className="grid-2"><div className="field"><label htmlFor="rubric">Rubric ID</label><input id="rubric" className="input" value={rubricId} onChange={(e) => setRubricId(e.target.value)} /></div><div className="field"><label htmlFor="rubric-digest">Rubric digest</label><input id="rubric-digest" className="input" value={rubricDigest} onChange={(e) => setRubricDigest(e.target.value)} /></div><div className="field"><label htmlFor="rubric-uri">Published rubric URI</label><input id="rubric-uri" className="input" type="url" value={rubricUri} onChange={(e) => setRubricUri(e.target.value)} /></div><div className="field"><label htmlFor="rubric-version">Version</label><input id="rubric-version" className="input" type="number" min="1" value={rubricVersion} onChange={(e) => setRubricVersion(Number(e.target.value))} /></div></div>}<button className="pill pill-primary">{authenticated ? "Review and sign" : "Sign in to attest"}</button></div></form><section className="panel form-panel"><p className="eyebrow">Reviewer invitation</p><div className="cluster"><label className="field grow"><span>Reviewer email or wallet</span><input className="input" value={invitee} onChange={(e) => setInvitee(e.target.value)} /></label><button className="pill pill-secondary align-end" onClick={invite}>Create invitation</button></div></section>{status && <p className="operation-status" role="status">{status}</p>}</div>;
}
export function ReviewActions(props: { contributionId: `0x${string}` }) { return process.env.NEXT_PUBLIC_PRIVY_APP_ID ? <Actions {...props} /> : <section className="panel form-panel"><span className="badge" data-tone="pending">Privy configuration required for writes</span></section>; }
