"use client";
import { usePrivy, useWallets } from "@privy-io/react-auth";
import { useState } from "react";
import { encodeFunctionData, keccak256, stringToHex } from "viem";
import { advanceOperation, beginOperation, establishPrivySession, uploadPublicFile } from "@/lib/browser-wallet";
import { canonicalJson, validatePublicUrl } from "@/lib/integrity";
import { contracts } from "@/lib/contracts.generated";
import { privyAppId } from "@/lib/config";
import { useAttestiaWrite } from "@/lib/use-attestia-write";

function Controls({ attestationId, contributionId }: { attestationId: `0x${string}`; contributionId: string }) {
  const { authenticated, login, getAccessToken } = usePrivy(); const { wallets } = useWallets(); const [reason, setReason] = useState(""); const [evidence, setEvidence] = useState(""); const [status, setStatus] = useState("");
  const { writeContract } = useAttestiaWrite();
  async function auth() { if (!authenticated) { login(); throw new Error("Sign in to continue"); } const wallet = wallets[0]; const token = await getAccessToken(); if (!wallet || !token) throw new Error("Session expired"); await establishPrivySession(token, wallet.address); return wallet; }
  async function revoke() { try { const wallet = await auth(); if (reason.trim().length < 10) throw new Error("Explain the revocation in at least 10 characters"); const body = canonicalJson({ schema: "attestia.revocation.v1", attestationId, reason, createdAt: new Date().toISOString() }); const digest = keccak256(stringToHex(body)); const uploaded = await uploadPublicFile(new File([body], "revocation.json", { type: "application/json" })); const operation = await beginOperation("revoke_attestation", wallet.address, digest, attestationId); if (operation.transactionHash) { setStatus(`Already submitted ${operation.transactionHash}`); return; } await advanceOperation(operation.id, "awaiting_signature"); setStatus("Awaiting issuer signature…"); const data = encodeFunctionData({ ...contracts.AttestationRegistry, functionName: "revoke", args: [attestationId, digest, uploaded.uri] }); const { hash } = await writeContract({ wallet, to: contracts.AttestationRegistry.address, data }); await advanceOperation(operation.id, "submitted", hash); setStatus(`Revocation submitted ${hash}`); } catch (error) { setStatus(error instanceof Error ? error.message : "Revocation failed"); } }
  async function dispute() { try { await auth(); if (evidence) validatePublicUrl(evidence); const response = await fetch("/api/disputes", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ contributionId, attestationId, reason, evidenceURI: evidence || undefined }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error.message); setStatus(`Dispute annotation saved ${body.id}. Active counts remain unchanged.`); } catch (error) { setStatus(error instanceof Error ? error.message : "Dispute failed"); } }
  return <section className="panel form-panel"><p className="eyebrow">Lifecycle controls</p><h1 className="section-title">Revoke or dispute</h1><div className="stack composer-fields"><div className="field"><label htmlFor="reason">Public reason</label><textarea id="reason" className="input" value={reason} onChange={(e) => setReason(e.target.value)} /></div><div className="field"><label htmlFor="evidence">Dispute evidence URL (optional)</label><input id="evidence" className="input" value={evidence} onChange={(e) => setEvidence(e.target.value)} type="url" /></div><div className="cluster"><button className="pill pill-secondary" onClick={revoke}>Revoke as issuer</button><button className="pill pill-quiet" onClick={dispute}>Annotate dispute</button></div><p className="muted form-note">A dispute adds context and preserves active onchain counts. Revocation is permanent and only the claim issuer can sign it.</p>{status && <p className="operation-status" role="status">{status}</p>}</div></section>;
}
export function RevokeDispute(props: { attestationId: `0x${string}`; contributionId: string }) { return privyAppId() ? <Controls {...props} /> : <section className="panel form-panel"><span className="badge" data-tone="pending">Privy configuration required</span></section>; }
