"use client";
import { useState } from "react";
import { CheckCircle, WarningCircle } from "@phosphor-icons/react";

export function Verifier({ initialType = "contribution", initialId = "" }: { initialType?: string; initialId?: string }) {
  const [type, setType] = useState(["contribution", "profile", "attestation"].includes(initialType) ? initialType : "contribution"); const [id, setId] = useState(initialId); const [result, setResult] = useState<{ error?: { code: string; message: string; correlationId: string }; integrity?: { status: string; expected: string; actual?: string; reason?: string } } | null>(null); const [loading, setLoading] = useState(false);
  async function verify(event: React.FormEvent) { event.preventDefault(); setLoading(true); const response = await fetch(`/api/verify?type=${type}&id=${encodeURIComponent(id)}`); setResult(await response.json()); setLoading(false); }
  const integrity = result?.integrity; const status = integrity?.status;
  return <div className="verify-grid"><form className="panel verify-form" onSubmit={verify}><p className="eyebrow">Public verification</p><h1 className="section-title">Check the evidence trail</h1><p className="lede">Read the Monad record and reproduce its metadata digest independently.</p><div className="stack composer-fields"><div className="field"><label htmlFor="record-type">Record type</label><select className="input" id="record-type" value={type} onChange={(e) => setType(e.target.value)}><option value="contribution">Contribution</option><option value="profile">Profile</option><option value="attestation">Attestation</option></select></div><div className="field"><label htmlFor="record-id">Record ID</label><input className="input" id="record-id" value={id} onChange={(e) => setId(e.target.value)} placeholder="0x…" required pattern="0x[0-9a-fA-F]{64}" /></div><button className="pill pill-primary" disabled={loading}>{loading ? "Verifying…" : "Verify record"}</button></div></form>
  <section className="panel verify-result" aria-live="polite">{!result ? <div className="empty-result"><span className="brand-mark">?</span><h2>No record checked yet</h2><p>Verification reads public chain and metadata endpoints. It never needs a wallet.</p></div> : result.error || !integrity ? <div><WarningCircle size={36} className="danger" /><h2>{result.error?.code ?? "INVALID_RESPONSE"}</h2><p>{result.error?.message ?? "The verification service returned an invalid response."}</p>{result.error?.correlationId && <code>{result.error.correlationId}</code>}</div> : <div><span className="badge" data-tone={status === "verified" ? "active" : "danger"}>{status === "verified" ? <CheckCircle /> : <WarningCircle />}{status}</span><h2>Integrity result</h2><dl className="review-list"><div><dt>Expected</dt><dd>{integrity.expected}</dd></div><div><dt>Reproduced</dt><dd>{integrity.actual ?? integrity.reason}</dd></div><div><dt>Network</dt><dd>Monad Testnet · 10143</dd></div></dl><button className="pill pill-secondary" onClick={() => { const blob = new Blob([JSON.stringify(result, null, 2)], { type: "application/json" }); const link = document.createElement("a"); link.href = URL.createObjectURL(blob); link.download = `attestia-${id}.json`; link.click(); URL.revokeObjectURL(link.href); }}>Export JSON</button></div>}</section></div>;
}
